language: node_js
script: "npm run travis"
node_js:
  - iojs
  - "0.12"
  - "0.11"
  - "0.10"
  - "4"
  - "5"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
